insert into "users" ("username", "hashedPassword", "firstName", "lastName", "email", "location", "createdAt", "profileImageUrl")
values ('JJPhoto', '$argon2i$v=19$m=4096,t=3,p=1$1vBhuypyqVCGBhjO+DTNOw$vi4YFWchBDncjIImG7vKoy5OmeCftIpNHfh5azX2OBQ', 'John', 'Johnson', 'john_johnson@surfr.com', 'Sydney, Australia', now(), 'https://surfr-photographer.s3.amazonaws.com/surfphoto.jpg'),
       ('Iceman', '$argon2i$v=19$m=4096,t=3,p=1$inX5J2FWgxACcwC5R4hGEQ$BzINoYGfaGqQnb4zxS53YiAJaCnJBpkgpVLcPOjlz9U', 'Chris', 'Smith', 'Chris_Smith@surfr.com', 'Pismo Beach, California', now(), 'https://surfr-photographer.s3.amazonaws.com/guy-kawasaki-iij-QvyRAnM-unsplash.jpg'),
       ('Banzai808', '$argon2i$v=19$m=4096,t=3,p=1$QGlFaTAbR7tckZztVyaIjg$RDBn+jnwGU4msAgkafeTEqYr/QrlGe7pTjEs18KGXng', 'CJ', 'Markson', 'CJ@surfr.com', 'North Shore, Oahu', now(), 'https://surfr-photographer.s3.amazonaws.com/example6.jpg'),
       ('ocean', '$argon2i$v=19$m=4096,t=3,p=1$d3pW2N6YK8fLeyabvLoxDw$Zy2rFRr3+uMkqVUkLBBkSAyyz/1aLAKptV9QIFZuajc', 'Luisa', 'Portorella', 'Luisa@surfr.com', 'San Clemente, California', now(), 'https://surfr-photographer.s3.amazonaws.com/surfr.png'),
       ('Chicama', '$argon2i$v=19$m=4096,t=3,p=1$PFS6vT/ybz3DdqCJcLMqWw$dV0k0GT5UfXL7/ufTIwuw02BJQZh74MZytpfIUmtWJ4', 'Pedro', 'Larriviere', 'Pedro@surfr.com', 'Chicama, Peru', now(), 'https://surfr-photographer.s3.amazonaws.com/profileImage.jpg');

insert into "photos" ("userId", "imageUrl", "createdAt")
values (1, 'https://surfr-photographer.s3.amazonaws.com/example1.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/example2.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/example3.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/example4.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/lacie-slezak-7yqyQQXgOT8-unsplash.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/kevin-jiner-hv9Rn0qtNzM-unsplash.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/knut-robinson-v-7gLbhrQ7o-unsplash.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/kristin-wilson-MLdBupMri0g-unsplash.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/leandro-fregoni-1lynGkBhqHA-unsplash.jpg', now()),
       (1, 'https://surfr-photographer.s3.amazonaws.com/example5.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example6.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example7.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example8.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example9.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example10.jpg', now()),
       (2, 'https://surfr-photographer.s3.amazonaws.com/example11.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/1491584691760.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/jeremy-bishop-zam3m6W2npM-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/johny-goerend-XWWKKdG4Arg-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/knut-robinson-TAV8ARy0TB4-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/knut-robinson-kPF0LrAfPWg-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/knut-robinson-v-7gLbhrQ7o-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/kristin-wilson-MLdBupMri0g-unsplash.jpg', now()),
       (3, 'https://surfr-photographer.s3.amazonaws.com/lacie-slezak-7yqyQQXgOT8-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/marvin-meyer-fQgRGhMRoEo-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/oliver-sjostrom-Mc-r-wjnAac-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/sam-wermut-35muyqODIHA-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/steven-wilcox-FlXGsR5nCqk-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/tim-marshall-hIHh4E4_OGA-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/trevor-gerzen-r_XS7sml57o-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/tyler-nix-6mze64HRU2Q-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/vladimir-kudinov-RKiMg1bwsMY-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/addy-mae-xeYEAvDdUqU-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/blake-hunter-p01IGh_HxtM-unsplash.jpg', now()),
       (4, 'https://surfr-photographer.s3.amazonaws.com/cedric-frixon-G9Rfc1qccH4-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/francesca-noemi-marconi-5s77ByGM2Lw-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/guy-kawasaki-iij-QvyRAnM-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/istockphoto-1326407314-170667a.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/jeremy-bishop-OXMX3R0KKx0-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/jeremy-bishop-oBL3j_GiSUk-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/kaspars-upmanis--TA-2O1XIQo-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/jeremy-bishop-pikyGuAmwpM-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/lachlan-dempsey-O14abKtZ5iY-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/leonor-oom-PGeZNaocvkU-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/marvin-meyer-fQgRGhMRoEo-unsplash.jpg', now()),
       (5, 'https://surfr-photographer.s3.amazonaws.com/knut-robinson-0g-XKvP1GFY-unsplash.jpg', now());
